app: 
    resource: "@AppBundle/Controller/" 
    type: annotation

    # app/config/routing.yml
login_route:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

login_check:
    path: /login_check
    # no controller is bound to this route
    # as it's handled by the Security system