AppBundle\Entity\Person:
    type: entity
    table: null
    repositoryClass: AppBundle\Entity\PersonRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        levelId:
            type: integer
            column: level_id
        firstName:
            type: string
            length: '20'
            column: first_name
        lastName:
            type: string
            length: '20'
            column: last_name
        registerDate:
            type: datetime
            column: register_date
        email:
            type: string
            length: '40'
        phonenumber:
            type: string
            length: '20'
        password:
            type: string
            length: '20'
    lifecycleCallbacks: {  }
