AppBundle\Entity\Person_Answer:
    type: entity
    table: null
    repositoryClass: AppBundle\Entity\Person_AnswerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        questionId:
            type: integer
            column: question_id
        answerContent:
            type: string
            length: '100'
            column: answer_content
    lifecycleCallbacks: {  }
