<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Person_AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Person_AnswerRepository extends EntityRepository
{
}
