<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Question_CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Question_CategoryRepository extends EntityRepository
{
}
