<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Questionnaire_QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Questionnaire_QuestionRepository extends EntityRepository
{
}
