<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Question_TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Question_TypeRepository extends EntityRepository
{
}
