<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Sent_QuestionnaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sent_QuestionnaireRepository extends EntityRepository
{
}
